server:
  port: 8082
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    port: 2181
    timeout: 15000

